### ISSUE TITLE
Last change in sensor.py

### ISSUE THREAD

**Issue by jnrksv** [Hellowlol/ha-tide#1]
## Configuration

```yaml

File "/config/custom_components/tide/sensor.py", line 25, in <module>
vol.Required(CONF_LATITUDE, default=""): vol.latitude,
AttributeError: module 'voluptuous' has no attribute 'latitude'.

```

## Describe the bug
Latest change in sensor.py causes HA hanging . Had to charge back to previous to get HA up and running.

## Debug log

```text



```

**Comment by Hellowlol** [comment]
Should be fixed now. Thanks for the report.
