### ISSUE TITLE
No module named 'pendulum'

### ISSUE THREAD

**Issue by andilge** [Hellowlol/ha-tide#2]
Hi Hellowlol,

1st, thnx for sharing this integration on HACS and followed all steps listed on
https://github.com/Hellowlol/ha-tide

and have added
```yaml
- platform: tide
  longitude: redacted
  latitude: redacted
```
in my sensors yaml.

I constantly get theses error messages now:
ERROR (MainThread) [homeassistant.components.hassio] Platform error sensor.tide - No module named 'pendulum'

These are my hardware details (hass.io on Synology):

arch | x86_64
dev | false
docker | true
hassio | true
os_name | Linux
os_version | 4.4.59+
python_version | 3.7.6
timezone | America/Fortaleza
version | 0.107.1
virtualenv | false

**Lovelace**
mode | storage
resources | 0
views | 2

Please point me in the right direction about missing module pendulum.

**Comment by Hellowlol** [comment]
For now you can install the nordpool integration as this uses pendum and it will install it for you.

You can manually update the manifest.json and add "pendulum>=2.0"to the requirements key. I’ll push a update for this later.

**Comment by andilge** [comment]
Sorry, there is no official nordpool integration for HA, please follow 
https://www.home-assistant.io/integrations/#search/nordpool
to verify

**Comment by andilge** [comment]
tried altering manifest,json to
```json
{
  "domain": "tide",
  "name": "Tide",
  "documentation": "https://github.com/Hellowlol/ha-tide",
  "dependencies": [],
  "config_flow": true,
  "codeowners": [
    "@hellowlol"
  ],
  "requirements": "pendulum>=2.0",
  "homeassistant": "0.96.0"
}
```

and continue having error messages like
2020-03-20 11:09:36 ERROR (MainThread) [homeassistant.components.hassio] Platform error sensor.tide - No module named 'pendulum'

Are the cornered brackets mandatory in config entry requirements (analogue codeowner)?

**Comment by Hellowlol** [comment]
No, the nordpool is in HACS

Sendt fra min iPhone

**Comment by Hellowlol** [comment]
Should be fixed with the latest commit.

**Comment by andilge** [comment]
tested with positive result, thank you so much.
