### ISSUE TITLE
ha-tide doesn't change state

### ISSUE THREAD

**Issue by jnrksv** [Hellowlol/ha-tide#4]
## Version of the custom_component

7984530

## Configuration

```yaml
Integration used according to the documentation.

```

## Describe the bug
At this moment (13:30 local time) high tide has passed with an hour, but the sensor still show that state is "Flow".
![tide](https://user-images.githubusercontent.com/24974747/78132100-6de74200-741c-11ea-8f14-8ba18fc32a87.PNG)
 

## Debug log

```text

Not attached because there's no point in displaying an empty log.

```

**Comment by Hellowlol** [comment]
Thanks for the report. I only verified that the tide sensor didn’t give any errors 🤦‍♂️

**Comment by Hellowlol** [comment]
Should be fixed now. If not enable debug log with:

````
logger:
  default: warning
  logs:
    custom_components.tide: debug
````
post the log and reopen the issue
